#!/bin/bash 

# choose problem 
problem=0

# choose polynomial order (0, 1, 2, 3)
polorder=2

#choose grid type
# valid are: ALUGRID_SIMPLEX, ALUGRID_CONFORM, ALUGRID_CUBE,
# ALBERTAGRID, SGRID, UGGRID YASPGRID , ONEDGRID
gridtype=ALUGRID_SIMPLEX

# choose diffusion 
epsilonne=0.0001

# choose grape display every step (0 = disabled)
grape=0

# choose start refinement level 
level=0

# choose repeats of eoc loop
repeats=1

# choose dimension (1, 2, or 3)
dimw=2

if ! make GRIDTYPE=${gridtype} GRIDDIM=${dimw} POLORDER=${polorder} PROBLEM=${problem} dgtest;
then
echo "Something went wrong"
exit 1
fi
./dgtest grid${dimw}d.dgf ${repeats} ${level} ${epsilonne} ${grape}
mv eoc.tex ${gridtype}_pol${polorder}_p${problem}_eps${epsilonne}.tex
pdflatex ${gridtype}_pol${polorder}_p${problem}_eps${epsilonne}.tex
rm -f *.{aux,log}

exit 0
