dune-istl: Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType > Class Template Reference (dune-istl )
Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType > Class Template Reference
[ISTL Communication]
#include <owneroverlapcopy.hh>
Detailed Description
template<class GlobalIdType, class LocalIdType>
class Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >
A class setting up standard communication for a two-valued attribute set with owner/overlap/copy semantics.
set up communication from known distribution with owner/overlap/copy semantics
Public Types
typedef ParallelIndexSet
< GlobalIdType, LI, 512 > ParallelIndexSet
The type of the parallel index set.
typedef RemoteIndices< PIS > RemoteIndices
The type of the remote indices.
typedef GlobalLookupIndexSet
< ParallelIndexSet > GlobalLookupIndexSet
The type of the reverse lookup of indices.
Public Member Functions
template<class T>
void copyOwnerToAll (const T &source, T &dest) const
Communicate values from owner data points to all other data points.
template<class T>
void addOwnerOverlapToAll (const T &source, T &dest) const
Communicate values from owner data points to all other data points and add them to those values.
template<class T1, class T2>
void dot (const T1 &x, const T1 &y, T2 &result) const
Compute a global dot product of two vectors.
template<class T1>
double norm (const T1 &x) const
Compute the global euclidian norm of a vector.
const ParallelIndexSet & indexSet () const
Get the underlying parallel index set.
const RemoteIndices & remoteIndices () const
Get the underlying remote indices.
ParallelIndexSet & indexSet ()
Get the underlying parallel index set.
RemoteIndices & remoteIndices ()
Get the underlying remote indices.
template<class T1>
void project (T1 &x) const
Set vector to zero at copy dofs.
OwnerOverlapCopyCommunication (MPI_Comm comm_)
Construct the communication without any indices.
OwnerOverlapCopyCommunication (const IndexInfoFromGrid< GlobalIdType, LocalIdType > &indexinfo, MPI_Comm comm_)
Constructor.
Constructor & Destructor Documentation
template<class GlobalIdType, class LocalIdType> Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::OwnerOverlapCopyCommunication (MPI_Comm comm_) [inline]
Construct the communication without any indices.
The local index set and the remote indices have to be set up later on.
Parameters:
comm_ The MPI Communicator to use, e. g. MPI_COMM_WORLD
template<class GlobalIdType, class LocalIdType> Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::OwnerOverlapCopyCommunication (const IndexInfoFromGrid< GlobalIdType, LocalIdType > & indexinfo, MPI_Comm comm_) [inline]
Constructor.
Parameters:
indexinfo The set of IndexTripels describing the local and remote indices.
comm_ The communicator to use in the communication.
References Dune::ParallelIndexSet< TG, TL, N >::add(), Dune::ParallelIndexSet< TG, TL, N >::begin(), Dune::ParallelIndexSet< TG, TL, N >::beginResize(), Dune::ParallelIndexSet< TG, TL, N >::end(), Dune::ParallelIndexSet< TG, TL, N >::endResize(), Dune::RemoteIndexListModifier< T, mode >::insert(), Dune::IndexInfoFromGrid< G, L >::localIndices(), Dune::IndexInfoFromGrid< G, L >::remoteIndices(), and Dune::RemoteIndices< T >::setIndexSets().
Member Function Documentation
template<class GlobalIdType, class LocalIdType> template<class T> void Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::copyOwnerToAll (const T & source, T & dest) const [inline]
Communicate values from owner data points to all other data points.
source The data to send from. dest The data to send to.
References Dune::BufferedCommunicator< T >::free().
template<class GlobalIdType, class LocalIdType> template<class T> void Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::addOwnerOverlapToAll (const T & source, T & dest) const [inline]
Communicate values from owner data points to all other data points and add them to those values.
source The data to send from. dest The data to add them communicated values to.
References Dune::BufferedCommunicator< T >::free().
template<class GlobalIdType, class LocalIdType> template<class T1, class T2> void Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::dot (const T1 & x, const T1 & y, T2 & result) const [inline]
Compute a global dot product of two vectors.
Parameters:
x The first vector of the product.
y The second vector of the product.
result Reference to store the result in.
References Dune::ParallelIndexSet< TG, TL, N >::begin(), and Dune::ParallelIndexSet< TG, TL, N >::end().
template<class GlobalIdType, class LocalIdType> template<class T1> double Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::norm (const T1 & x) const [inline]
Compute the global euclidian norm of a vector.
Parameters:
x The vector to compute the norm of.
Returns:
The global euclidian norm of that vector.
References Dune::ParallelIndexSet< TG, TL, N >::begin(), and Dune::ParallelIndexSet< TG, TL, N >::end().
template<class GlobalIdType, class LocalIdType> const ParallelIndexSet& Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::indexSet () const [inline]
Get the underlying parallel index set.
Returns:
The underlying parallel index set.
template<class GlobalIdType, class LocalIdType> const RemoteIndices& Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::remoteIndices () const [inline]
Get the underlying remote indices.
Returns:
The underlying remote indices.
template<class GlobalIdType, class LocalIdType> ParallelIndexSet& Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::indexSet () [inline]
Get the underlying parallel index set.
Returns:
The underlying parallel index set.
template<class GlobalIdType, class LocalIdType> RemoteIndices& Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::remoteIndices () [inline]
Get the underlying remote indices.
Returns:
The underlying remote indices.
template<class GlobalIdType, class LocalIdType> template<class T1> void Dune::OwnerOverlapCopyCommunication< GlobalIdType, LocalIdType >::project (T1 & x) const [inline]
Set vector to zero at copy dofs.
Parameters:
x The vector to project.
References Dune::ParallelIndexSet< TG, TL, N >::begin(), and Dune::ParallelIndexSet< TG, TL, N >::end().
The documentation for this class was generated from the following file:
owneroverlapcopy.hh