dune-grid: Dune::CombinedGrapeDisplay< DisplayType > Class Template Reference (dune-grid )
Dune::CombinedGrapeDisplay< DisplayType > Class Template Reference
#include <combinedgrapedisplay.hh>
Detailed Description
template<class DisplayType>
class Dune::CombinedGrapeDisplay< DisplayType >
Combines GrapeDataDisplays to one so that visualisation for parallel grid is more easy to handle.
Public Member Functions
CombinedGrapeDisplay ()
Constructor, make a GrapeGridDisplay for given grid.
~CombinedGrapeDisplay ()
Destructor for GrapeGridDisplay.
void addDisplay (DisplayType &disp)
add display to list of displays
void display ()
void * getHmesh ()
return pointer to Grape Hmesh
Public Attributes
void * hmesh_
pointer to hmesh
Protected Member Functions
void evalCoord (DUNE_ELEM *he, DUNE_FDATA *df, const double *coord, double *val)
calles evalCoord for data of actual display
void evalDof (DUNE_ELEM *he, DUNE_FDATA *df, int localNum, double *val)
calles evalDof for data of actual display
Static Protected Member Functions
static void evalCoordWrap (DUNE_ELEM *he, DUNE_FDATA *df, const double *coord, double *val)
static void evalDofWrap (DUNE_ELEM *he, DUNE_FDATA *df, int localNum, double *val)
Member Function Documentation
template<class DisplayType> void Dune::CombinedGrapeDisplay< DisplayType >::display () [inline]
Calls the display of the grid and draws the discrete function if discretefunction is NULL, then only the grid is displayed
References Dune::CombinedGrapeDisplay< DisplayType >::hmesh_.
template<class DisplayType> void Dune::CombinedGrapeDisplay< DisplayType >::evalCoordWrap (DUNE_ELEM * he, DUNE_FDATA * df, const double * coord, double * val) [inline, static, protected]
functions pointer for calling evaluate in ghmesh just calles evalCoord for actual display
References Dune::CombinedGrapeDisplay< DisplayType >::evalCoord().
Referenced by Dune::CombinedGrapeDisplay< DisplayType >::addDisplay().
template<class DisplayType> void Dune::CombinedGrapeDisplay< DisplayType >::evalDofWrap (DUNE_ELEM * he, DUNE_FDATA * df, int localNum, double * val) [inline, static, protected]
functions pointer for calling evaluate in ghmesh just calles evalDof for actual display
References Dune::CombinedGrapeDisplay< DisplayType >::evalDof().
Referenced by Dune::CombinedGrapeDisplay< DisplayType >::addDisplay().
The documentation for this class was generated from the following files:
combinedgrapedisplay.hh
combinedgrapedisplay.cc