dune-grid: Dune::ALU2dGridHierarchicIndexSet< dim, dimworld > Class Template Reference (dune-grid )
Dune::ALU2dGridHierarchicIndexSet< dim, dimworld > Class Template Reference
#include <indexsets.hh>
Detailed Description
template<int dim, int dimworld>
class Dune::ALU2dGridHierarchicIndexSet< dim, dimworld >
hierarchic index set of ALU2dGrid
Public Types
typedef int IndexType
type of index (in upcomming version this is unsigned int)
Public Member Functions
template<class EntityType>
int index (const EntityType &ep) const
return hierarchic index of given entity
template<int cd>
int subIndex (const EntityCodim0Type &ep, int i) const
return subIndex of given entity
int size (GeometryType type) const
int size (int codim) const
return size of indexset, i.e. maxindex+1
const std::vector< GeometryType > & geomTypes (int codim) const
deliver all geometry types used in this grid
template<int cd, PartitionIteratorType pitype>
ALU2dGridHierarchicIteratorTypes
< GridType >::template Codim
< cd >::template Partition
< pitype >::Iterator end () const
Iterator to one past the last entity of given codim for partition type.
template<int cd, PartitionIteratorType pitype>
ALU2dGridHierarchicIteratorTypes
< GridType >::template Codim
< cd >::template Partition
< pitype >::Iterator begin () const
Iterator to first entity of given codimension and partition type.
template<class EntityType>
bool contains (const EntityType &) const
return true because all entities are contained in this set
template<int cc>
int subIndex (const typename remove_const< GridImp >::type::Traits::template Codim< 0 >::Entity &e, int i) const
Return total number of entities of given codim as a sum for all geometry types in this index set.
Index access from entity
template<int cc>
int index (const typename remove_const< GridImp >::type::Traits::template Codim< cc >::Entity &e) const
Map entity to index. The result of calling this method with an entity that is not in the index set is undefined.
Member Function Documentation
template<int dim, int dimworld> int Dune::ALU2dGridHierarchicIndexSet< dim, dimworld >::size (GeometryType type) const [inline]
return size of indexset, i.e. maxindex+1 for given type, if type is not exisiting within grid 0 is returned
Reimplemented from Dune::IndexSet< GridImp, IndexSetImp, IndexSetTypes >.
References Dune::ALU2dGrid< dim, dimworld >::geomTypes(), and Dune::ALU2dGrid< dim, dimworld >::hierSetSize().
Referenced by Dune::ALU2dGridLocalIdSet< dim, dimworld >::id(), and Dune::ALU2dGridLocalIdSet< dim, dimworld >::subId().
template<class GridImp, class IndexSetImp, class IndexSetTypes> template<int cc> int Dune::IndexSetDefaultImplementation< GridImp, IndexSetImp, IndexSetTypes >::subIndex (const typename remove_const< GridImp >::type::Traits::template Codim< 0 >::Entity & e, int i) const [inline, inherited]
Return total number of entities of given codim as a sum for all geometry types in this index set.
Parameters:
codim A valid codimension Map subentity of codim 0 entity to index.
e Reference to codim 0 entity.
i Number of codim cc subentity of e, where cc is the template parameter of the function.
Returns:
An index in the range 0 ... Max number of entities in set - 1. Here the method entity of Entity is used to get the subEntity and then the index of this Entity is returned.
Reimplemented from Dune::IndexSet< GridImp, IndexSetImp, IndexSetTypes >.
template<class GridImp, class IndexSetImp, class IndexSetTypes> template<int cc> int Dune::IndexSet< GridImp, IndexSetImp, IndexSetTypes >::index (const typename remove_const< GridImp >::type::Traits::template Codim< cc >::Entity & e) const [inline, inherited]
Map entity to index. The result of calling this method with an entity that is not in the index set is undefined.
Parameters:
e Reference to codim cc entity, where cc is the template parameter of the function.
Returns:
An index in the range 0 ... Max number of entities in set - 1.
Referenced by Dune::IndexSetDefaultImplementation< Dune::ALU3dGrid< dim, dimworld, elType >, Dune::ALU3dGridHierarchicIndexSet< dim, dimworld, elType >, Dune::ALU3dGridHierarchicIteratorTypes< Dune::ALU3dGrid< dim, dimworld, elType > > >::contains(), Dune::IndexSetDefaultImplementation< Dune::ALU3dGrid< dim, dimworld, elType >, Dune::ALU3dGridHierarchicIndexSet< dim, dimworld, elType >, Dune::ALU3dGridHierarchicIteratorTypes< Dune::ALU3dGrid< dim, dimworld, elType > > >::subIndex(), and Dune::GnuplotWriter< GridType, IndexSet >::write().
The documentation for this class was generated from the following file:
alugrid/2d/indexsets.hh