dune-grid: Dune::AlbertaGridHierarchicIterator< GridImp > Class Template Reference (dune-grid )
Dune::AlbertaGridHierarchicIterator< GridImp > Class Template Reference
#include <agrid.hh>
Detailed Description
template<class GridImp>
class Dune::AlbertaGridHierarchicIterator< GridImp >
Mesh entities of codimension 0 ("elements") allow to visit all entities of codimension 0 obtained through nested, hierarchic refinement of the entity. Iteration over this set of entities is provided by the HIerarchicIterator, starting from a given entity. This is redundant but important for memory efficient implementations of unstru hierarchically refined meshes.
Public Types
typedef
AlbertaGridEntityPointer< cd,
GridImp > AlbertaGridEntityPointerType
typedef of my type
enum
codimension of entity pointer
Public Member Functions
AlbertaGridHierarchicIterator (const GridImp &grid, ALBERTA TRAVERSE_STACK *travStack, int actLevel, int maxLevel, bool leafIt)
the normal Constructor
AlbertaGridHierarchicIterator (const GridImp &grid, int actLevel, int maxLevel)
the default Constructor
AlbertaGridHierarchicIterator (const AlbertaGridHierarchicIterator< GridImp > &org)
the default Constructor
AlbertaGridHierarchicIterator
< GridImp > & operator= (const AlbertaGridHierarchicIterator< GridImp > &org)
the default Constructor
void increment ()
increment
bool equals (const AlbertaGridEntityPointerType &i) const
equality
Entity & dereference () const
dereferencing
int level () const
ask for level of entities
void done ()
has to be called when iterator is finished
Protected Member Functions
bool leafIt () const
returns true if entity comes from LeafIterator
EntityImp & entityImp ()
return reference to internal entity imp
const EntityImp & entityImp () const
return const reference to internal entity imp
Protected Attributes
bool isLeaf_
flag for leaf iterators
Constructor & Destructor Documentation
template<class GridImp> Dune::AlbertaGridHierarchicIterator< GridImp >::AlbertaGridHierarchicIterator (const AlbertaGridHierarchicIterator< GridImp > & org) [inline]
the default Constructor
get the actual used enInfo
References ManageTravStack::create(), Dune::AlbertaGridEntityPointer< 0, GridImp >::done(), Dune::AlbertaGridEntity< cd, dim, GridImp >::getElInfo(), ManageTravStack::getStack(), Dune::AlbertaGridHierarchicIterator< GridImp >::manageStack_, Dune::AlbertaGridEntity< cd, dim, GridImp >::setElInfo(), Dune::AlbertaGridEntity< cd, dim, GridImp >::setTraverseStack(), and Dune::AlbertaGridHierarchicIterator< GridImp >::virtualEntity_.
The documentation for this class was generated from the following files:
agrid.hh
albertagrid.cc