dune-grid: Dune::ALU3dGridEntity< 0, dim, GridImp > Class Template Reference (dune-grid )
Dune::ALU3dGridEntity< 0, dim, GridImp > Class Template Reference
#include <entity.hh>
Detailed Description
template<int dim, class GridImp>
class Dune::ALU3dGridEntity< 0, dim, GridImp >
A Grid is a container of grid entities. An entity is parametrized by the codimension. An entity of codimension c in dimension d is a d-c dimensional object.
Entities of codimension 0 ("elements") are defined through template specialization. Note that this specialization has an extended interface compared to the general case
Entities of codimension 0 allow to visit all neighbors, where a neighbor is an entity of codimension 0 which has a common entity of codimension 1 with the These neighbors are accessed via an iterator. This allows the implementation of non-matching meshes. The number of neigbors may be different from the number of faces/edges of an element!
Public Types
enum
know your own codimension
enum
know your own dimension
enum
Know dimension of the entity.
enum
know your own dimension of world
typedef ct ctype
define type used for coordinates in grid module
Public Member Functions
ALU3dGridEntity (const GridImp &grid, int level)
Constructor creating empty Entity.
ALU3dGridEntity (const ALU3dGridEntity &org)
copy Constructor
int level () const
level of this element
const Geometry & geometry () const
geometry of this entity
GeometryType type () const
type of geometry of this entity
PartitionType partitionType () const
return partition type of this entity (see grid.hh)
template<int cc>
int count () const
template<int cc>
Codim< cc >::EntityPointer entity (int i) const
ALU3dGridLeafIntersectionIteratorType ileafbegin () const
ALU3dGridLeafIntersectionIteratorType ileafend () const
Reference to one past the last intersection with neighbor.
ALU3dGridLevelIntersectionIteratorType ilevelbegin () const
ALU3dGridLevelIntersectionIteratorType ilevelend () const
Reference to one past the last intersection with neighbor.
bool isLeaf () const
returns true if Entity is leaf (i.e. has no children)
EntityPointer father () const
const Geometry & geometryInFather () const
ALU3dGridHierarchicIterator
< GridImp > hbegin (int maxlevel) const
ALU3dGridHierarchicIterator
< GridImp > hend (int maxlevel) const
Returns iterator to one past the last son.
bool wasRefined () const
returns true, if entity was created during last adaptation cycle
bool mightBeCoarsened () const
returns true, if entity might be coarsened during next adaptation cycle
bool hasBoundaryIntersections () const
returns true, if entity has intersections with boundary
bool mark (int refCount) const
int getMark () const
return current adaptation mark for this entity
void setElement (ALU3DSPACE HElementType &element)
void setGhost (ALU3DSPACE HBndSegType &ghost)
set original element pointer to fake entity
void reset (int l)
set actual walk level
void removeElement ()
set item pointer to NULL
bool equals (const ALU3dGridEntity< 0, dim, GridImp > &org) const
compare 2 entities, which means compare the item pointers
template<int cc>
int getSubIndex (int i) const
Member Function Documentation
template<int dim, class GridImp> template<int cc> int Dune::ALU3dGridEntity< 0, dim, GridImp >::count () const [inline]
Intra-element access to entities of codimension cc > codim. Return number of entities with codimension cc.
template<int dim, class GridImp> template<int cc> ALU3dGridEntity< 0, dim, GridImp >::template Codim< cc >::EntityPointer Dune::ALU3dGridEntity< 0, dim, GridImp >::entity (int i) const [inline]
Provide access to mesh entity i of given codimension. Entities are numbered 0 ... count<cc>()-1
References Dune::ALU3dGridEntity< cd, dim, GridImp >::level().
template<int dim, class GridImp> ALU3dGridEntity< 0, dim, GridImp >::ALU3dGridLeafIntersectionIteratorType Dune::ALU3dGridEntity< 0, dim, GridImp >::ileafbegin () const [inline]
Access to intersection with neighboring elements that are leaf elements. A neighbor is an entity of codimension 0 which has an entity of codimension 1 in commen with this entity. Access to neighbors is provided using iterators. This allows meshes to be nonmatching. Returns iterator referencing the first neighbor.
template<int dim, class GridImp> ALU3dGridEntity< 0, dim, GridImp >::ALU3dGridLevelIntersectionIteratorType Dune::ALU3dGridEntity< 0, dim, GridImp >::ilevelbegin () const [inline]
Intra-level access to intersection with neighboring elements. A neighbor is an entity of codimension 0 which has an entity of codimension 1 in commen with this entity. Access to neighbors is provided using iterators. This allows meshes to be nonmatching. Returns iterator referencing the first neighbor.
template<int dim, class GridImp> ALU3dGridEntity< 0, dim, GridImp >::EntityPointer Dune::ALU3dGridEntity< 0, dim, GridImp >::father () const [inline]
Inter-level access to father element on coarser grid. Assumes that meshes are nested.
template<int dim, class GridImp> const ALU3dGridEntity< 0, dim, GridImp >::Geometry & Dune::ALU3dGridEntity< 0, dim, GridImp >::geometryInFather () const [inline]
Location of this element relative to the reference element of the father. This is sufficient to interpolate all dofs in conforming case. Nonconforming may require access to neighbors of father and computations with local coordinates. On the fly case is somewhat inefficient since dofs are visited several times. If we store interpolation matrices, this is tolerable. We assume that on-the-fly implementation of numerical algorithms is only done for simple discretizations. Assumes that meshes are nested.
References Dune::ALU3dGridEntity< cd, dim, GridImp >::geometry().
template<int dim, class GridImp> ALU3dGridHierarchicIterator< GridImp > Dune::ALU3dGridEntity< 0, dim, GridImp >::hbegin (int maxlevel) const [inline]
Inter-level access to son elements on higher levels<=maxlevel. This is provided for sparsely stored nested unstructured meshes. Returns iterator to first son.
template<int dim, class GridImp> bool Dune::ALU3dGridEntity< 0, dim, GridImp >::mark (int refCount) const [inline]
marks an element for refCount refines. if refCount is negative the element is coarsend -refCount times mark returns true if element was marked, otherwise false
References Dune::ALU3dGridEntity< cd, dim, GridImp >::level().
template<int dim, class GridImp> void Dune::ALU3dGridEntity< 0, dim, GridImp >::setElement (ALU3DSPACE HElementType & element) [inline]
private methods, but public because of datahandle and template arguments of these methods
template<int dim, class GridImp> template<int cc> int Dune::ALU3dGridEntity< 0, dim, GridImp >::getSubIndex (int i) const [inline]
return index of sub entity with codim = cc and local number i i.e. return global number of vertex i for use in hierarchical index set
The documentation for this class was generated from the following files:
alugrid/3d/entity.hh
3d/entity_imp.cc