dune-grid: Dune::ALU2dGridGeometry< mydim, cdim, GridImp > Class Template Reference (dune-grid )
Dune::ALU2dGridGeometry< mydim, cdim, GridImp > Class Template Reference
#include <geometry.hh>
Detailed Description
template<int mydim, int cdim, class GridImp>
class Dune::ALU2dGridGeometry< mydim, cdim, GridImp >
Defines the geometry part of a mesh entity. Works for all dimensions, element types and dimensions of world. Provides reference element and mapping between local and global coordinates. The element may have different implementations because the mapping can be done more efficient for structured meshes than for unstructured meshes.
dim: An element is a polygonal in a hyperplane of dimension dim. 0 <= dim <= 2 is typically dim=0 is a point.
dimworld: Each corner is a point with dimworld coordinates. ALU2dGridGeometry Empty definition, needs to be specialized for element type
Public Member Functions
ALU2dGridGeometry ()
ALU2dGridGeometry (const int child, const int orientation)
constructor building geometry in father
const GeometryType & type () const
int corners () const
return the number of corners of this element. Corners are numbered 0...n-1
const FieldVector< alu2d_ctype,
cdim > & operator[] (int i) const
access to coordinates of corners. Index is the number of the corner
FieldVector< alu2d_ctype, cdim > global (const FieldVector< alu2d_ctype, mydim > &local) const
FieldVector< alu2d_ctype, mydim > local (const FieldVector< alu2d_ctype, cdim > &global) const
bool checkInside (const FieldVector< alu2d_ctype, mydim > &local) const
returns true if the point in local coordinates is inside reference element
alu2d_ctype integrationElement (const FieldVector< alu2d_ctype, mydim > &local) const
A(l) , see grid.hh.
alu2d_ctype volume () const
return volume of geometry
const FieldMatrix< alu2d_ctype,
mydim, mydim > & jacobianInverseTransposed (const FieldVector< alu2d_ctype, mydim > &local) const
can only be called for dim=dimworld!
bool builtGeom (const ALU2DSPACE Vertex &item, int)
Methods that not belong to the Interface, but have to be public.
bool builtGeom (const HElementType &item, int face)
built Geometry
template<class GeometryType, class LocalGeomType>
bool builtLocalGeom (const GeometryType &geo, const LocalGeomType &lg)
bool builtLocalGeom (const int faceNumber, const int twist)
build local geometry given local face number
FieldVector< alu2d_ctype, cdim > & getCoordVec (int i)
return non-const reference to coord vecs
void print (std::ostream &ss) const
print internal data
bool buildGeomInFather (const Geometry &fatherGeom, const Geometry &myGeom)
build geometry with local coords of child in reference element
template<>
FieldVector< alu2d_ctype, 2 > global (const FieldVector< alu2d_ctype, 0 > &local) const
template<>
alu2d_ctype volume () const
return volume of the geometry
template<>
alu2d_ctype volume () const
return volume of the geometry
Constructor & Destructor Documentation
template<int mydim, int cdim, class GridImp> Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::ALU2dGridGeometry () [inline]
for makeRefGeometry == true a Geometry with the coordinates of the reference element is made
Member Function Documentation
template<int mydim, int cdim, class GridImp> const GeometryType & Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::type () const [inline]
return the element type identifier line , triangle or tetrahedron, depends on dim
return the element type identifier line , triangle or tetrahedron, depends on dim
template<int mydim, int cdim, class GridImp> int Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::corners () const [inline]
return the number of corners of this element. Corners are numbered 0...n-1
return the number of corners of this element. Corners are numbered 0...mydim+1
Referenced by Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::operator[](), and Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::print().
template<int mydim, int cdim, class GridImp> FieldVector< alu2d_ctype, cdim > Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::global (const FieldVector< alu2d_ctype, mydim > & local) const [inline]
maps a local coordinate within reference element to global coordinate in element
maps a local coordinate within reference element to global coordinate in element
Referenced by Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::local().
template<int mydim, int cdim, class GridImp> FieldVector< alu2d_ctype, mydim > Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::local (const FieldVector< alu2d_ctype, cdim > & global) const [inline]
maps a global coordinate within the element to a local coordinate in its reference element
maps a global coordinate within the element to a local coordinate in its reference element
References Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::global().
Referenced by Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::checkInside().
template<int mydim, int cdim, class GridImp> bool Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::builtGeom (const ALU2DSPACE Vertex & item, int) [inline]
Methods that not belong to the Interface, but have to be public.
built Geometry
generate the geometry for out of given ALU2dGridElement
Referenced by Dune::ALU2dGridEntity< 0, dim, GridImp >::geometry(), and Dune::ALU2dGridEntity< cd, dim, GridImp >::geometry().
template<int mydim, int cdim, class GridImp> template<class GeometryType, class LocalGeometryType> bool Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::builtLocalGeom (const GeometryType & geo, const LocalGeometryType & lg) [inline]
build geometry for intersectionSelfLocal and intersectionNeighborLocal
template<int mydim, int cdim, class GridImp> void Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::print (std::ostream & ss) const [inline]
print internal data
print the GeometryInformation
References Dune::ALU2dGridGeometry< mydim, cdim, GridImp >::corners().
template<> FieldVector< alu2d_ctype, 2 > Dune::ALU2dGridGeometry< 0, 2, const ALU2dGrid< 2, 2 > >::global (const FieldVector< alu2d_ctype, 0 > & local) const [inline]
maps a local coordinate within reference element to global coordinate in element
The documentation for this class was generated from the following files:
alugrid/2d/geometry.hh
2d/geometry_imp.cc