dune-grid: Dune::AlbertaGridEntity< 0, dim, GridImp > Class Template Reference (dune-grid )
Dune::AlbertaGridEntity< 0, dim, GridImp > Class Template Reference
#include <agrid.hh>
Detailed Description
template<int dim, class GridImp>
class Dune::AlbertaGridEntity< 0, dim, GridImp >
A Grid is a container of grid entities. An entity is parametrized by the codimension. An entity of codimension c in dimension d is a d-c dimensional object.
Entities of codimension 0 ("elements") are defined through template specialization. Note that this specialization has an extended interface compared to the general case
Entities of codimension 0 allow to visit all neighbors, where a neighbor is an entity of codimension 0 which has a common entity of codimension 1 with the These neighbors are accessed via an iterator. This allows the implementation of non-matching meshes. The number of neigbors may be different from the number of faces/edges of an element!
Public Types
enum
know your own codimension
enum
know your own dimension
enum
Know dimension of the entity.
enum
know your own dimension of world
typedef ct ctype
define type used for coordinates in grid module
Public Member Functions
~AlbertaGridEntity ()
AlbertaGridEntity (const GridImp &grid, int level, bool leafIt)
Constructor, real information is set via setElInfo method.
int level () const
level of this element
int boundaryId () const
index of the boundary which is associated with the entity, 0 for inner entities
const Geometry & geometry () const
geometry of this entity
GeometryType type () const
type of geometry of this entity
template<int cc>
int count () const
< Default codim 1 Faces and codim == dim Vertices
template<int cc>
Codim< cc >::EntityPointer entity (int i) const
AlbertaGridLeafIntersectionIteratorType ileafbegin () const
AlbertaGridIntersectionIteratorType ileafend () const
Reference to one past the last intersection with neighbor.
bool isLeaf () const
returns true if entity is leaf entity, i.e. has no children
EntityPointer father () const
const Geometry & geometryInFather () const
AlbertaGridHierarchicIterator
< GridImp > hbegin (int maxlevel) const
AlbertaGridHierarchicIterator
< GridImp > hend (int maxlevel) const
Returns iterator to one past the last son.
bool wasRefined () const
Returns true, if entity was refined during last adaptation cycle.
bool mightBeCoarsened () const
Returns true, if entity might be coarsened during next adaption cycle.
bool hasBoundaryIntersections () const
Returns true, if entity has intersections with boundary.
PartitionType partitionType () const
return partition type of this entity (see grid.hh)
bool equals (const AlbertaGridEntity< 0, dim, GridImp > &i) const
equality of entities
Constructor & Destructor Documentation
template<int dim, class GridImp> Dune::AlbertaGridEntity< 0, dim, GridImp >::~AlbertaGridEntity () [inline]
Destructor, needed perhaps needed for deleteing faceEntity_ and edgeEntity_ , see below there are only implementations for dim==dimworld 2,3
Member Function Documentation
template<int dim, class GridImp> template<int cc> int Dune::AlbertaGridEntity< 0, dim, GridImp >::count () const [inline]
< Default codim 1 Faces and codim == dim Vertices
Intra-element access to entities of codimension cc > codim. Return number of entities with codimension cc.
template<int dim, class GridImp> template<int cc> AlbertaGridEntity< 0, dim, GridImp >::template Codim< cc >::EntityPointer Dune::AlbertaGridEntity< 0, dim, GridImp >::entity (int i) const [inline]
Provide access to mesh entity i of given codimension. Entities are numbered 0 ... count<cc>()-1
References Dune::AlbertaGridEntity< cd, dim, GridImp >::level().
template<int dim, class GridImp> AlbertaGridEntity< 0, dim, GridImp >::AlbertaGridLeafIntersectionIteratorType Dune::AlbertaGridEntity< 0, dim, GridImp >::ileafbegin () const [inline]
Provide access to mesh entity i of given codimension. Entities are numbered 0 ... count<cc>()-1
Intra-level access to intersection with neighboring elements. A neighbor is an entity of codimension 0 which has an entity of codimension 1 in commen with this entity. Access to neighbors is provided using iterators. This allows meshes to be nonmatching. Returns iterator referencing the first neighbor.
References Dune::AlbertaGridEntityPointer< cd, GridImp >::level().
template<int dim, class GridImp> AlbertaGridEntity< 0, dim, GridImp >::EntityPointer Dune::AlbertaGridEntity< 0, dim, GridImp >::father () const [inline]
Inter-level access to father element on coarser grid. Assumes that meshes are nested.
template<int dim, class GridImp> const Geometry& Dune::AlbertaGridEntity< 0, dim, GridImp >::geometryInFather () const
Location of this element relative to the reference element of the father. This is sufficient to interpolate all dofs in conforming case. Nonconforming may require access to neighbors of father and computations with local coordinates. On the fly case is somewhat inefficient since dofs are visited several times. If we store interpolation matrices, this is tolerable. We assume that on-the-fly implementation of numerical algorithms is only done for simple discretizations. Assumes that meshes are nested. NOTE: the imeplementation at the moment is very inefficient.
template<int dim, class GridImp> AlbertaGridHierarchicIterator< GridImp > Dune::AlbertaGridEntity< 0, dim, GridImp >::hbegin (int maxlevel) const [inline]
Inter-level access to son elements on higher levels<=maxlevel. This is provided for sparsely stored nested unstructured meshes. Returns iterator to first son.
References Dune::AlbertaGridEntityPointer< cd, GridImp >::leafIt(), and Dune::AlbertaGridEntityPointer< cd, GridImp >::level().
The documentation for this class was generated from the following files:
agrid.hh
albertagrid.cc