dune-grid: Dune::DefaultLevelIndexSet< GridImp > Class Template Reference (dune-grid )
Dune::DefaultLevelIndexSet< GridImp > Class Template Reference
#include <defaultindexsets.hh>
Detailed Description
template<class GridImp>
class Dune::DefaultLevelIndexSet< GridImp >
DefaultLevelIndexSet creates a LevelIndexSet for a Grid by using its HierarchicIndexSet.
Public Types
typedef int IndexType
type of index (in upcomming version this is unsigned int)
Public Member Functions
DefaultLevelIndexSet (const GridType &grid, int level)
template<class EntityType>
int index (const EntityType &en) const
return LevelIndex of given entity
template<int cd>
int index (const typename GridImp::template Codim< cd >::Entity &en) const
return LevelIndex of given entity
template<int cd>
int subIndex (const typename GridType::template Codim< 0 >::Entity &en, int i) const
template<class EntityType>
bool contains (const EntityType &en) const
returns true if this set provides an index for given entity
int size (int codim) const
return size of IndexSet for a given level and codim
int size (GeometryType type) const
void calcNewIndex ()
const std::vector< GeometryType > & geomTypes (int codim) const
deliver all geometry types used in this grid
template<int cd, PartitionIteratorType pitype>
DefaultLevelIteratorTypes
< GridImp >::template Codim
< cd >::template Partition
< pitype >::Iterator begin () const
Iterator to first entity of given codimension and partition type.
template<int cd, PartitionIteratorType pitype>
DefaultLevelIteratorTypes
< GridImp >::template Codim
< cd >::template Partition
< pitype >::Iterator end () const
Iterator to one past the last entity of given codim for partition type.
bool containsIndex (int cd, int idx) const
returns true if this set provides an index for given entity
template<int cc>
int subIndex (const typename remove_const< GridImp >::type::Traits::template Codim< 0 >::Entity &e, int i) const
Return total number of entities of given codim as a sum for all geometry types in this index set.
Index access from entity
template<int cc>
int index (const typename remove_const< GridImp >::type::Traits::template Codim< cc >::Entity &e) const
Map entity to index. The result of calling this method with an entity that is not in the index set is undefined.
Constructor & Destructor Documentation
template<class GridImp> Dune::DefaultLevelIndexSet< GridImp >::DefaultLevelIndexSet (const GridType & grid, int level) [inline]
create LevelIndex by using the HierarchicIndexSet of a grid for the given level
References Dune::DefaultLevelIndexSet< GridImp >::calcNewIndex().
Member Function Documentation
template<class GridImp> template<int cd> int Dune::DefaultLevelIndexSet< GridImp >::subIndex (const typename GridType::template Codim< 0 >::Entity & en, int i) const [inline]
return subIndex (LevelIndex) for a given Entity of codim = 0 and a given SubEntity codim and number of SubEntity
template<class GridImp> int Dune::DefaultLevelIndexSet< GridImp >::size (GeometryType type) const [inline]
return size of IndexSet for a given level and codim this method is to be revised
Reimplemented from Dune::IndexSet< GridImp, IndexSetImp, IndexSetTypes >.
References Dune::Grid< dim, dimworld, ct, GridFamily >::dimension.
template<class GridImp> void Dune::DefaultLevelIndexSet< GridImp >::calcNewIndex () [inline]
do calculation of the index set, has to be called when grid was changed or if index set is created
Referenced by Dune::DefaultLevelIndexSet< GridImp >::DefaultLevelIndexSet().
template<class GridImp, class IndexSetImp, class IndexSetTypes> template<int cc> int Dune::IndexSetDefaultImplementation< GridImp, IndexSetImp, IndexSetTypes >::subIndex (const typename remove_const< GridImp >::type::Traits::template Codim< 0 >::Entity & e, int i) const [inline, inherited]
Return total number of entities of given codim as a sum for all geometry types in this index set.
Parameters:
codim A valid codimension Map subentity of codim 0 entity to index.
e Reference to codim 0 entity.
i Number of codim cc subentity of e, where cc is the template parameter of the function.
Returns:
An index in the range 0 ... Max number of entities in set - 1. Here the method entity of Entity is used to get the subEntity and then the index of this Entity is returned.
Reimplemented from Dune::IndexSet< GridImp, IndexSetImp, IndexSetTypes >.
template<class GridImp, class IndexSetImp, class IndexSetTypes> template<int cc> int Dune::IndexSet< GridImp, IndexSetImp, IndexSetTypes >::index (const typename remove_const< GridImp >::type::Traits::template Codim< cc >::Entity & e) const [inline, inherited]
Map entity to index. The result of calling this method with an entity that is not in the index set is undefined.
Parameters:
e Reference to codim cc entity, where cc is the template parameter of the function.
Returns:
An index in the range 0 ... Max number of entities in set - 1.
Referenced by Dune::IndexSetDefaultImplementation< Dune::ALU3dGrid< dim, dimworld, elType >, Dune::ALU3dGridHierarchicIndexSet< dim, dimworld, elType >, Dune::ALU3dGridHierarchicIteratorTypes< Dune::ALU3dGrid< dim, dimworld, elType > > >::contains(), Dune::IndexSetDefaultImplementation< Dune::ALU3dGrid< dim, dimworld, elType >, Dune::ALU3dGridHierarchicIndexSet< dim, dimworld, elType >, Dune::ALU3dGridHierarchicIteratorTypes< Dune::ALU3dGrid< dim, dimworld, elType > > >::subIndex(), and Dune::GnuplotWriter< GridType, IndexSet >::write().
The documentation for this class was generated from the following file:
defaultindexsets.hh