dune-grid: Dune::LeafAmiraMeshWriter< GridType > Class Template Reference (dune-grid )
Dune::LeafAmiraMeshWriter< GridType > Class Template Reference
[AmiraMesh]
#include <amirameshwriter.hh>
Detailed Description
template<class GridType>
class Dune::LeafAmiraMeshWriter< GridType >
Provides file writing facilities in the AmiraMesh format for leaf grids.
Public Member Functions
LeafAmiraMeshWriter ()
Default constructor.
LeafAmiraMeshWriter (const GridType &grid)
Constructor which initializes the AmiraMesh object with a given leaf grid.
template<class GridType2, class IndexSetType2>
void addGrid (const GridType2 &grid, const IndexSetType2 &indexSet, bool splitQuads=false)
Add grid with a given index set.
template<class GridType2>
void addLevelGrid (const GridType2 &grid, int level, bool splitQuads=false)
Add level grid.
template<class GridType2>
void addLeafGrid (const GridType2 &grid, bool splitQuads=false)
Add leaf grid.
template<class GridType2, class DataContainer>
void addCellData (const DataContainer &data, const GridType2 &grid)
Add cell data.
template<class DataContainer>
void addVertexData (const DataContainer &data, const IndexSetType &indexSet)
Add vertex data.
void write (const std::string &filename, bool ascii=false) const
Write AmiraMesh object to disk.
Static Public Member Functions
static void writeGrid (const GridType &grid, const std::string &filename)
Write a grid in AmiraMesh format.
template<class VectorType>
static void writeBlockVector (const GridType &grid, const VectorType &f, const std::string &filename)
Writes an ISTL block vector in AmiraMesh format.
Member Function Documentation
template<class GridType> static void Dune::LeafAmiraMeshWriter< GridType >::writeGrid (const GridType & grid, const std::string & filename) [inline, static]
Write a grid in AmiraMesh format.
Parameters:
grid The grid objects that is to be written
filename The filename
References Dune::AmiraMeshWriter< GridType, IndexSetType >::write().
template<class GridType> template<class VectorType> static void Dune::LeafAmiraMeshWriter< GridType >::writeBlockVector (const GridType & grid, const VectorType & f, const std::string & filename) [inline, static]
Writes an ISTL block vector in AmiraMesh format.
Parameters:
grid The grid objects that the vector lives on
f The vector to be written. Has to comply with the ISTL conventions
filename The filename
References Dune::AmiraMeshWriter< GridType, IndexSetType >::addVertexData(), Dune::YaspGrid< dim, dimworld >::leafIndexSet(), and Dune::AmiraMeshWriter< GridType, IndexSetType >::write().
template<class GridType, class IndexSetType> template<class GridType2, class IndexSetType2> void Dune::AmiraMeshWriter< GridType, IndexSetType >::addGrid (const GridType2 & grid, const IndexSetType2 & indexSet, bool splitQuads = false) [inline, inherited]
Add grid with a given index set.
Parameters:
grid Grid to be written
indexSet Index set of the grid section to be written
splitQuads Amira doesn't support 2d quad grids. If this is set any quadrilateral will be split in two triangles. If not, the file is not readable by standard Amira.
References Dune::Grid< dim, dimworld, ct, GridFamily >::dimensionworld, Dune::ReferenceCube< ctype, dim >::type(), and Dune::ReferenceSimplex< ctype, dim >::type().
Referenced by Dune::AmiraMeshWriter< GridType, IndexSetType >::addLeafGrid(), and Dune::AmiraMeshWriter< GridType, IndexSetType >::addLevelGrid().
template<class GridType, class IndexSetType> template<class GridType2> void Dune::AmiraMeshWriter< GridType, IndexSetType >::addLevelGrid (const GridType2 & grid, int level, bool splitQuads = false) [inline, inherited]
Add level grid.
Parameters:
grid Grid to be written
indexSet Level of the level grid that is to be written
splitQuads Amira doesn't support 2d quad grids. If this is set any quadrilateral will be split in two triangles. If not, the file is not readable by standard Amira.
References Dune::AmiraMeshWriter< GridType, IndexSetType >::addGrid().
Referenced by Dune::LevelAmiraMeshWriter< GridType >::LevelAmiraMeshWriter().
template<class GridType, class IndexSetType> template<class GridType2> void Dune::AmiraMeshWriter< GridType, IndexSetType >::addLeafGrid (const GridType2 & grid, bool splitQuads = false) [inline, inherited]
Add leaf grid.
Parameters:
grid Grid to be written
splitQuads Amira doesn't support 2d quad grids. If this is set any quadrilateral will be split in two triangles. If not, the file is not readable by standard Amira.
References Dune::AmiraMeshWriter< GridType, IndexSetType >::addGrid().
Referenced by Dune::LeafAmiraMeshWriter< GridType >::LeafAmiraMeshWriter().
template<class GridType, class IndexSetType> template<class DataContainer> void Dune::AmiraMeshWriter< GridType, IndexSetType >::addVertexData (const DataContainer & data, const IndexSetType & indexSet) [inline, inherited]
Add vertex data.
Parameters:
An ISTL compliant vector type
IndexSet of the grid that the data belongs to
Todo:
Auto-detect data type
References Dune::Grid< dim, dimworld, ct, GridFamily >::dimension.
Referenced by Dune::LeafAmiraMeshWriter< GridType >::writeBlockVector(), and Dune::LevelAmiraMeshWriter< GridType >::writeBlockVector().
template<class GridType, class IndexSetType> void Dune::AmiraMeshWriter< GridType, IndexSetType >::write (const std::string & filename, bool ascii = false) const [inline, inherited]
Write AmiraMesh object to disk.
Parameters:
filename Name of the file to write to
ascii Set this if you want an ascii AmiraMesh file
Referenced by Dune::LeafAmiraMeshWriter< GridType >::writeBlockVector(), Dune::LevelAmiraMeshWriter< GridType >::writeBlockVector(), Dune::LeafAmiraMeshWriter< GridType >::writeGrid(), and Dune::LevelAmiraMeshWriter< GridType >::writeGrid().
The documentation for this class was generated from the following file:
amirameshwriter.hh