dune-grid: ManageTravStack Class Reference (dune-grid )
ManageTravStack Class Reference
#include <albertaextra.hh>
Detailed Description
organize the TRAVERSE_STACK Management, so we can use the nice Albert functions get_traverse_stack and free_traverse_stack this count the copy made of this class and call free_traverse_stack only if no more copies left
Public Member Functions
ManageTravStack ()
initialize the member variables
ManageTravStack (const ManageTravStack &copy)
if a copy is made, the refcout is increased
void create ()
~ManageTravStack ()
set Stack free, if no more refences exist
TRAVERSE_STACK * getStack () const
return the TRAVERSE_STACK pointer for use
Member Function Documentation
void ManageTravStack::create () [inline]
get new TRAVERSE_STACK using the original Albert Routine get_traverse_stack, which get an new or free stack
Referenced by Dune::AlbertaGridHierarchicIterator< GridImp >::AlbertaGridHierarchicIterator(), Dune::AlbertaGridTreeIterator< cd, pitype, GridImp >::AlbertaGridTreeIterator(), Dune::AlbertaGridTreeIterator< cd, pitype, GridImp >::operator=(), and Dune::AlbertaGridHierarchicIterator< GridImp >::operator=().
The documentation for this class was generated from the following file:
albertaextra.hh